# Exemplo simples de Cluster EKS customizado:
# Criado por Breno Carvalho (https://brenocarvalho.cloud)
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ClusterCloud
  region: us-east-1 # ${AWS_REGION} 
#  version: "1.18"
vpc:
  id: "vpc-xxxxxxxxxxx"  # Altere o VPC ID para a VPC que está criada no seu ambiente.
  cidr: "10.x.x.x/16"       # Altera para o CIRD da VPC que está criada.
  subnets:
    private:
      us-east-1a:
        id: "subnet-xxxxxxxxxx" # (Especifique o Subnet ID da da primeira Subnet privada)
      us-east-1b:
        id: "subnet-xxxxxxxxxx" # (Especifique o Subnet ID da da segunda Subnet privada)
    # Subnets Publicas
    public:
      us-east-1a: 
        id: "subnet-xxxxxxxxxxx" # (Especifique o Subnet ID da da primeira Subnet publica)
      us-east-1b:
        id: "subnet-xxxxxxxxxxx" # (Especifique o Subnet ID da da segunda Subnet publica)
managedNodeGroups:
  # Nodegroup redes privadas
  - name: ng-private
    instanceType: t3.small
    desiredCapacity: 2
    minSize: 2
    maxSize: 4
    privateNetworking: true
    subnets:
      - subnet-xxxxxxxxxxxxxxxxx # (Especifique o Subnet ID da da primeira Subnet privada)
      - subnet-xxxxxxxxxxxxxxxxx # (Especifique o Subnet ID da da segunda Subnet privada)
  # Nodegroup redes publicas
  - name: ng-public
    instanceType: t3.small
    desiredCapacity: 2
    minSize: 2
    maxSize: 4
    subnets:
      - subnet-xxxxxxxxxxxxxxxxx # (Especifique o Subnet ID da da primeira Subnet publica)
      - subnet-xxxxxxxxxxxxxxxxx # (Especifique o Subnet ID da da segunda Subnet publica)
    ssh:
      enableSsm: true
    iam:
      withAddonPolicies:
        albIngress: true
        autoScaler: true
        cloudWatch: true
cloudWatch:
    clusterLogging:
        # Ativar os logs 
        enableTypes: ["*"]
        # all supported types: "api", "audit", "authenticator", "controllerManager", "scheduler"
        # supported special values: "*" and "all"
secretsEncryption: 
  keyARN: ${MASTER_ARN}
